project:
  type: website
  output-dir: docs

website:
  title: "Janette Avelar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Current Projects
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: resources.qmd
        text: Resources
      - href: teaching.qmd
        text: Teaching
      - href: about.qmd
        text: About/CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
